import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Provider from "./provider";
import "./styles/global.css";
import General from "./components/General/general";
import Content from "./components/Footer/Content/content";
import FooterContent from "./components/Footer/footer";
const RobotoFont = Roboto({
  weight: ["400", "700", "300", "500"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Demo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={RobotoFont.className}>
        <Provider>
          <General>
            <>{children}</>
            <FooterContent>
              <Content />
            </FooterContent>
          </General>
        </Provider>
      </body>
    </html>
  );
}
